-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Correctional_Facilities"
(
    "Correctional_Facility_ID" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Correctional_Facility_Name" text COLLATE pg_catalog."default" NOT NULL,
    "Facility_Sec_Level" text COLLATE pg_catalog."default",
    "Avg_Cost_Per_Employee_Hour_USD" numeric NOT NULL,
    "Average_Daily_Inmate_Population" integer NOT NULL,
    "Average_Inmate_to_CO_Ratio" integer NOT NULL,
    CONSTRAINT "Correctional_Facilities_pkey" PRIMARY KEY ("Correctional_Facility_ID")
);

CREATE TABLE IF NOT EXISTS public."Inmate_Details"
(
    "Inmate_ID" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Correctional_Facility_ID" integer NOT NULL,
    "Gender" text COLLATE pg_catalog."default" NOT NULL,
    "Race" text COLLATE pg_catalog."default" NOT NULL,
    "Age_at_Release" text COLLATE pg_catalog."default" NOT NULL,
    "Residence_PUMA" integer NOT NULL,
    "Gang_Affiliated" boolean,
    "Supervision_Risk_Score_First" integer,
    "Supervision_Level_First" text COLLATE pg_catalog."default",
    "Education_Level" text COLLATE pg_catalog."default" NOT NULL,
    "Dependents" text COLLATE pg_catalog."default" NOT NULL,
    "Prison_Offense" text COLLATE pg_catalog."default",
    "Prison_Years" text COLLATE pg_catalog."default" NOT NULL,
    "Prior_Arrest_Episodes_Felony" text COLLATE pg_catalog."default" NOT NULL,
    "Prior_Arrest_Episodes_Misd" text COLLATE pg_catalog."default" NOT NULL,
    "Prior_Arrest_Episodes_Violent" text COLLATE pg_catalog."default" NOT NULL,
    "Prior_Arrest_Episodes_Property" text COLLATE pg_catalog."default" NOT NULL,
    "Prior_Arrest_Episodes_Drug" text COLLATE pg_catalog."default" NOT NULL,
    "Prior_Arrest_Episodes_PPViolationCharges" text COLLATE pg_catalog."default" NOT NULL,
    "Prior_Arrest_Episodes_DVCharges" boolean NOT NULL,
    "Prior_Arrest_Episodes_GunCharges" boolean NOT NULL,
    "Prior_Conviction_Episodes_Felony" text COLLATE pg_catalog."default" NOT NULL,
    "Prior_Conviction_Episodes_Misd" text COLLATE pg_catalog."default" NOT NULL,
    "Prior_Conviction_Episodes_Viol" boolean NOT NULL,
    "Prior_Conviction_Episodes_Prop" text COLLATE pg_catalog."default" NOT NULL,
    "Prior_Conviction_Episodes_Drug" text COLLATE pg_catalog."default" NOT NULL,
    "Prior_Conviction_Episodes_PPViolationCharges" boolean NOT NULL,
    "Prior_Conviction_Episodes_DomesticViolenceCharges" boolean NOT NULL,
    "Prior_Conviction_Episodes_GunCharges" boolean NOT NULL,
    "Prior_Revocations_Parole" boolean NOT NULL,
    "Prior_Revocations_Probation" boolean NOT NULL,
    "Condition_MH_SA" boolean NOT NULL,
    "Condition_Cog_Ed" boolean NOT NULL,
    "Condition_Other" boolean NOT NULL,
    "Violations_ElectronicMonitoring" boolean NOT NULL,
    "Violations_Instruction" boolean NOT NULL,
    "Violations_FailToReport" boolean NOT NULL,
    "Violations_MoveWithoutPermission" boolean NOT NULL,
    "Delinquency_Reports" text COLLATE pg_catalog."default" NOT NULL,
    "Program_Attendances" text COLLATE pg_catalog."default" NOT NULL,
    "Program_UnexcusedAbsences" text COLLATE pg_catalog."default" NOT NULL,
    "Residence_Changes" text COLLATE pg_catalog."default" NOT NULL,
    "Avg_Days_per_DrugTest" numeric,
    "DrugTests_THC_Positive" numeric,
    "DrugTests_Cocaine_Positive" numeric,
    "DrugTests_Meth_Positive" numeric,
    "DrugTests_Other_Positive" numeric,
    "Percent_Days_Employed" numeric,
    "Jobs_Per_Year" numeric,
    "Employment_Exempt" boolean NOT NULL,
    "Recidivism_Within_3years" boolean NOT NULL,
    "Recidivism_Arrest_Year1" boolean NOT NULL,
    "Recidivism_Arrest_Year2" boolean NOT NULL,
    "Recidivism_Arrest_Year3" boolean NOT NULL,
    CONSTRAINT "Inmate_Details_pkey" PRIMARY KEY ("Inmate_ID")
);

CREATE TABLE IF NOT EXISTS public."Residence_Prison Release_PUMA"
(
    "Release_PUMA_ID_Code" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "PUMAs_Included" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Residence_Prison Release_PUMA_pkey" PRIMARY KEY ("Release_PUMA_ID_Code")
);

CREATE TABLE IF NOT EXISTS public."EBRR_Program_Cohorts"
(
    "EBRR_Program_Cohort_ID" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Correctional_Facility_ID" integer NOT NULL,
    "EBRR_Programs_ID" integer NOT NULL,
    "Program_Cohort_Size_Max" integer,
    "Program_Cohort_Size_Min" integer,
    "Number_of_Cohorts" integer,
    "Program_Cohort_Num_Enrolled_Avg" integer,
    "Program_Cohort_Num_Attended_Avg" integer,
    "Program_Cohort_Num_Completed_Avg" integer,
    "Program_Cohort_Percent_Completion_Avg" numeric,
    "Program_Cohort_Attendance_Rate_Avg" numeric,
    "Program_Cohort_Hours_Avg" integer,
    "Num_Employee_Hours_Per_Cohort_Avg" integer,
    "Cost_Supply_Max_Per_Cohort _USD" integer,
    CONSTRAINT "EBRR_Program_Cohorts_pkey" PRIMARY KEY ("EBRR_Program_Cohort_ID")
);

CREATE TABLE IF NOT EXISTS public."EBRR_Programs"
(
    "EBRR_Programs_ID" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Correctional_Facility_ID" integer NOT NULL,
    "EBRR_CTE_Program" boolean NOT NULL,
    "EBRR_Skills_Training" boolean NOT NULL,
    "EBRR_Soft_Skills" boolean NOT NULL,
    "EBRR_Work_Ready" boolean NOT NULL,
    CONSTRAINT "EBRR_Programs_pkey" PRIMARY KEY ("EBRR_Programs_ID")
);

ALTER TABLE IF EXISTS public."Inmate_Details"
    ADD CONSTRAINT "Inmate_Details_Correctional_Facility_ID_fkey" FOREIGN KEY ("Correctional_Facility_ID")
    REFERENCES public."Correctional_Facilities" ("Correctional_Facility_ID") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_Inmate_Details_Correctional_Facility_ID_fkey"
    ON public."Inmate_Details"("Correctional_Facility_ID");


ALTER TABLE IF EXISTS public."Inmate_Details"
    ADD CONSTRAINT "Inmate_Details_Residence_PUMA_fkey" FOREIGN KEY ("Residence_PUMA")
    REFERENCES public."Residence_Prison Release_PUMA" ("Release_PUMA_ID_Code") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_Inmate_Details_Residence_PUMA_fkey"
    ON public."Inmate_Details"("Residence_PUMA");


ALTER TABLE IF EXISTS public."EBRR_Program_Cohorts"
    ADD CONSTRAINT "EBRR_Program_Cohorts_EBRR_Program_ID_fkey" FOREIGN KEY ("EBRR_Programs_ID")
    REFERENCES public."EBRR_Programs" ("EBRR_Programs_ID") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_EBRR_Program_Cohorts_EBRR_Program_ID_fkey"
    ON public."EBRR_Program_Cohorts"("EBRR_Programs_ID");


ALTER TABLE IF EXISTS public."EBRR_Program_Cohorts"
    ADD CONSTRAINT "EBRR_Programs_Cohorts_Correctional_Facility_ID_fkey" FOREIGN KEY ("Correctional_Facility_ID")
    REFERENCES public."Correctional_Facilities" ("Correctional_Facility_ID") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_EBRR_Programs_Cohorts_Correctional_Facility_ID_fkey"
    ON public."EBRR_Program_Cohorts"("Correctional_Facility_ID");


ALTER TABLE IF EXISTS public."EBRR_Programs"
    ADD CONSTRAINT "EBRR_Programs_Correctional_Facility_ID_fkey" FOREIGN KEY ("Correctional_Facility_ID")
    REFERENCES public."Correctional_Facilities" ("Correctional_Facility_ID") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;
CREATE INDEX IF NOT EXISTS "fki_EBRR_Programs_Correctional_Facility_ID_fkey"
    ON public."EBRR_Programs"("Correctional_Facility_ID");

END;